image: ruby:2.6

services:
  - postgres:11-alpine

variables:
  POSTGRES_DB: postgresdb
  CONTAINER_IMAGE: registry.gitlab.com/trekview/explorer

stages:
  - test
  - build

cache:
  paths:
    - .bundle
    - vendor/ruby

test:
  stage: test

  script:
    - apt-get update -qy
    - apt-get install -y nodejs
    - bundle install --path .bundle
    - cp .env
    - cp config/database.ci.yml config/database.yml
    - bundle exec rake db:create db:schema:load RAILS_ENV=test || true
    - bundle exec rake db:migrate RAILS_ENV=test
    - bundle exec rspec
    - bundle exec cucumber

build:
  stage: build

  image: docker:stable

  services:
    - docker:dind

  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

  script:
    - docker pull $CONTAINER_IMAGE:master || true
    - docker build --cache-from $CONTAINER_IMAGE:master --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME