version: '3.4'
services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: explorer_app_test
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs-current yarn
        - EXECJS_RUNTIME=Node
        - BUNDLE_WITHOUT=production
        - RAILS_ENV=test
    environment:
      RAILS_ENV: test
      DATABASE_HOST: db
      DATABASE_NAME: explorer-development
      DATABASE_USER_NAME: postgres
      DATABASE_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      SECRET_KEY_BASE: we-dont-need-a-secret-here
      ADMIN_EMAIL: exp-admin@example.com
      ADMIN_PASSWORD: password
      FOG_PROVIDER: AWS
      FOG_REGION: eu-west-2
    ports:
      - 3000
    links:
      - db

volumes:
  db-data:
