FROM ruby:2.6.3-alpine

ARG BUNDLE_WITHOUT
ARG DATABASE_URL
ARG SECRETE_KEY_BASE=foo
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_USER_NAME
ARG DATABASE_PASSWORD
ARG DATABASE_PORT
ARG ADMIN_EMAIL
ARG ADMIN_PASSWORD
ARG AWS_ACCESS_KEY_ID
ARG AWS_S3_BUCKET
ARG AWS_S3_BUCKET_REGION
ARG AWS_SECRET_ACCESS_KEY
ARG DEVISE_SENDER_EMAIL_ADDRESS
ARG DEVISE_SENDER_NAME='Trek View Staging'
ARG FOG_DIRECTORY
ARG FOG_PROVIDER
ARG FOG_REGION
ARG GOOGLE_ANALYTICS_KEY
ARG GOOGLE_MAPS_API_KEY
ARG LANG=en_US.UTF-8
ARG MAILCHIMP_AUDIENCE_ID
ARG RACK_ENV=staging
ARG RAILS_ENV=staging
ARG SITE_URL
ARG DISALLOW_ALL_WEB_CRAWLERS
ARG MAILCHIMP_API_KEY
ARG MAILGUN_DOMAIN
ARG MAILGUN_SMTP_LOGIN
ARG MAILGUN_SMTP_PASSWORD
ARG MAILGUN_SMTP_PORT=587
ARG MAILGUN_SMTP_SERVER
ARG MAILERLITE_API_KEY
ARG MAILERLITE_GROUP_ID
ARG MAPBOX_TOKEN

ENV BUNDLE_WITHOUT ${BUNDLE_WITHOUT}
ENV DATABASE_URL ${DATABASE_URL}
ENV SECRETE_KEY_BASE ${SECRETE_KEY_BASE}
ENV DATABASE_HOST ${DATABASE_HOST}
ENV DATABASE_NAME ${DATABASE_NAME}
ENV DATABASE_USER_NAME ${DATABASE_USER_NAME}
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}
ENV DATABASE_PORT ${DATABASE_PORT}
ENV ADMIN_EMAIL ${ADMIN_EMAIL}
ENV ADMIN_PASSWORD ${ADMIN_PASSWORD}
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_S3_BUCKET ${AWS_S3_BUCKET}
ENV AWS_S3_BUCKET_REGION ${AWS_S3_BUCKET_REGION}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV DEVISE_SENDER_EMAIL_ADDRESS ${DEVISE_SENDER_EMAIL_ADDRESS}
ENV DEVISE_SENDER_NAME ${DEVISE_SENDER_NAME}
ENV FOG_DIRECTORY ${FOG_DIRECTORY}
ENV FOG_PROVIDER ${FOG_PROVIDER}
ENV FOG_REGION ${FOG_REGION}
ENV GOOGLE_ANALYTICS_KEY ${GOOGLE_ANALYTICS_KEY}
ENV GOOGLE_MAPS_API_KEY ${GOOGLE_MAPS_API_KEY}
ENV LANG ${LANG}
ENV MAILCHIMP_AUDIENCE_ID ${MAILCHIMP_AUDIENCE_ID}
ENV RACK_ENV ${RACK_ENV}
ENV RAILS_ENV ${RAILS_ENV}
ENV SITE_URL ${SITE_URL}
ENV DISALLOW_ALL_WEB_CRAWLERS ${DISALLOW_ALL_WEB_CRAWLERS}
ENV MAILCHIMP_API_KEY ${MAILCHIMP_API_KEY}
ENV MAILGUN_DOMAIN ${MAILGUN_DOMAIN}
ENV MAILGUN_SMTP_LOGIN ${MAILGUN_SMTP_LOGIN}
ENV MAILGUN_SMTP_PASSWORD ${MAILGUN_SMTP_PASSWORD}
ENV MAILGUN_SMTP_PORT ${MAILGUN_SMTP_PORT}
ENV MAILGUN_SMTP_SERVER ${MAILGUN_SMTP_SERVER}
ENV RAILS_SERVE_STATIC_FILES=true
ENV MAILERLITE_API_KEY ${MAILERLITE_API_KEY}
ENV MAILERLITE_GROUP_ID ${MAILERLITE_GROUP_ID}
ENV MAPBOX_TOKEN ${MAPBOX_TOKEN}

RUN export

RUN apk update --no-cache && apk add build-base nodejs postgresql-dev git yarn tzdata imagemagick bash

RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler -v '2.0.2'
RUN bundle install --binstubs

COPY . .

# # Install yarn packages
# COPY package.json yarn.lock /app/
# RUN yarn install

# Precompile assets
RUN bundle exec rake assets:precompile

# Expose Puma port
EXPOSE 3000

LABEL maintainer="Ivanov Artem <ivanov.artem.1009@gmail.com>"

# CMD puma -C config/puma.rb

# Start up
CMD ["docker/startup.sh"]
