version: '3.7'

services:
  postgresdb:
    environment:
      - POSTGRES_PASSWORD=postgres
    hostname: db.explorer.trekview.com
    image: postgres:11-alpine
    ports:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /exp-volumes/explorer/postgresql:/var/lib/postgresql/data

  app: &app_base
    image: explorer_app_production
    build:
      context: .
      args:
        - FOLDERS_TO_REMOVE=spec node_modules app/assets vendor/assets lib/assets tmp/cache
        - BUNDLE_WITHOUT=development:test
        - EXECJS_RUNTIME=Disabled
        - RAILS_ENV=production
    environment:
      RAILS_ENV: production
      DATABASE_HOST: postgresdb
      DATABASE_NAME: explorer
      DATABASE_USER_NAME: postgres
      DATABASE_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      SECRET_KEY_BASE: we-dont-need-a-secret-here
      ADMIN_EMAIL: exp-admin@example.com
      ADMIN_PASSWORD: password
      FOG_PROVIDER: AWS
      FOG_REGION: eu-west-2
    hostname: app.explorer.trekview.com
    links:
      - postgresdb
    ports:
      - 3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5m
      start_period: 1m

