version: '3.4'
services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  app: &app_base
    image: explorer_app_development
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs-current yarn build-base git
        - EXECJS_RUNTIME=Node
        - RAILS_ENV=development
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_NAME: explorer
      DATABASE_USER_NAME: postgres
      DATABASE_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      ADMIN_EMAIL: exp-admin@example.com
      ADMIN_PASSWORD: password
      FOG_PROVIDER: AWS
      FOG_REGION: eu-west-2
    ports:
      - "3000"
    links:
      - db
    volumes:
      - .:/app

volumes:
  db-data:
